name: Check PR

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  pr-title:
    runs-on: ubuntu-latest
    name: Check PR Title
    permissions:
      contents: read
      issues: read
      pull-requests: read
    steps:
      - name: Check PR Title
        uses: agenthunt/conventional-commit-checker-action@f1823f632e95a64547566dcd2c7da920e67117ad # v2.0.1
        with:
          pr-title-regex: "^(build|chore|ci|docs|feat|fix|perf|refactor|style|test)(\\(.+\\))?(!)?:\\s.*"
          pr-body-regex: ".*" # We don't really care what the PR body description contains, just the title
